// A header file template for the DICE configuration header file
// generated by CMake.
// Author contact: valentin.perret@gmail.com

// Version information
#define DICE_VERSION_MAJOR 4
#define DICE_VERSION_MINOR 8

// Threading information
#define USE_THREADS 1
